import streamlit as st
import os
from dotenv import load_dotenv
import google.generativeai as genai
from PIL import Image
from fpdf import FPDF
import io

# -------------------------------
# Page Configuration & UI Enhancement
# -------------------------------
st.set_page_config(page_title="Civil Engineering Insight Studio", page_icon="🏗️", layout="wide")

# Custom CSS for Blue Title, Red Button, Animations, and Footer
st.markdown("""
    <style>
    .main-title {
        color: #004a99; 
        font-size: 42px;
        font-weight: 800;
        text-align: center;
        margin-top: 20px;
        animation: fadeInDown 1s ease-out;
    }
    
    .sub-text {
        text-align: center;
        color: #555;
        margin-bottom: 30px;
    }

    /* Red Browse Button Styling */
    div[data-testid="stFileUploader"] section button {
        background-color: #FF4B4B !important;
        color: white !important;
        border: none !important;
    }
    
    button[data-testid="stBaseButton-secondary"] {
        background-color: #FF4B4B !important;
        color: white !important;
    }

    /* Sticky Footer */
    .footer {
        position: fixed;
        left: 0;
        bottom: 0;
        width: 100%;
        background-color: white;
        color: #004a99;
        text-align: center;
        padding: 10px;
        font-weight: bold;
        border-top: 2px solid #004a99;
        z-index: 999;
    }

    @keyframes fadeInDown {
        0% { opacity: 0; transform: translateY(-20px); }
        100% { opacity: 1; transform: translateY(0); }
    }
    </style>
    
    <div class="main-title">🏗️ Civil Engineering Insight Studio</div>
    <div class="sub-text">Automated Structural Analysis, Safety Auditing, and Progress Documentation.</div>
    
    <div class="footer">
        Developed by Raja 2026
    </div>
    """, unsafe_allow_html=True)

# -------------------------------
# Load API Key
# -------------------------------
load_dotenv()
API_KEY = os.getenv("GOOGLE_API_KEY")

if not API_KEY:
    st.error("GOOGLE_API_KEY not found in .env file")
    st.stop()

# -------------------------------
# Configure Gemini
# -------------------------------
genai.configure(api_key=API_KEY)

try:
    available_models = [m.name for m in genai.list_models() if 'generateContent' in m.supported_generation_methods]
    MODEL_ID = "gemini-flash-latest"
    if f"models/{MODEL_ID}" not in available_models and MODEL_ID not in available_models:
        MODEL_ID = available_models[0]
    
    model = genai.GenerativeModel(MODEL_ID)
    st.sidebar.caption(f"Engine: {MODEL_ID}")
except Exception as e:
    st.error(f"Critical Error: {e}")
    st.stop()

# -------------------------------
# Helper Function: PDF Generation (FIXED FOR STREAMLIT)
# -------------------------------
def generate_pdf(text_content):
    pdf = FPDF()
    pdf.add_page()
    pdf.set_font("Arial", "B", 16)
    pdf.cell(0, 10, "Civil Engineering Insight Report", ln=True, align='C')
    pdf.set_font("Arial", size=10)
    pdf.cell(0, 10, "Generated by AI Structural Studio", ln=True, align='C')
    pdf.ln(10)
    
    pdf.set_font("Arial", size=11)
    # Convert text to Latin-1 and handle characters Arial doesn't support
    safe_text = text_content.encode('latin-1', 'replace').decode('latin-1')
    pdf.multi_cell(0, 8, safe_text)
    
    # Get the raw output from FPDF
    output = pdf.output(dest='S')
    
    # CRITICAL FIX: Ensure the output is converted to standard 'bytes'
    # Streamlit .download_button does not accept 'bytearray' in some versions
    return bytes(output)

# -------------------------------
# Streamlit UI Body
# -------------------------------
if "report_text" not in st.session_state:
    st.session_state.report_text = None

uploaded_file = st.file_uploader("Upload Structure Image", type=["jpg", "jpeg", "png"])

if uploaded_file:
    col1, col2 = st.columns([1, 1], gap="large")
    
    with col1:
        image = Image.open(uploaded_file)
        st.image(image, caption="Uploaded Site Photo", use_container_width=True)
        
        if st.button("Generate Engineering Report"):
            analysis_prompt = (
                "You are a Senior Structural and Safety Engineer. Analyze the attached image and provide a report with:\n\n"
                "1. RISK ASSESSMENT SCORE: Rate from Low to High based on visible site conditions.\n"
                "2. STRUCTURAL TYPE & MATERIALS: Identify the type of structure and primary materials used.\n"
                "3. CONSTRUCTION PHASE: Describe the current progress stage.\n"
                "4.  SAFETY ALERT FLAGS: Explicitly identify hazards like missing guardrails, "
                "unstable shoring, lack of PPE, or structural cracks.\n"
                "5. ENGINEERING INSIGHT: Describe load distribution or unique features."
            )

            with st.spinner("AI is analyzing structural components..."):
                try:
                    response = model.generate_content([analysis_prompt, image])
                    st.session_state.report_text = response.text
                except Exception as e:
                    st.error(f"Analysis error: {e}")

    with col2:
        if st.session_state.report_text:
            st.subheader("Engineering & Safety Report")
            st.markdown(st.session_state.report_text)
            
            st.divider()
            
            # Final PDF Fix: Wrap in bytes() to solve StreamlitAPIException
            try:
                final_pdf_data = generate_pdf(st.session_state.report_text)
                
                st.download_button(
                    label=" Download Report as PDF",
                    data=final_pdf_data,
                    file_name="Engineering_Safety_Report.pdf",
                    mime="application/pdf",
                    use_container_width=True
                )
            except Exception as e:
                st.error(f"PDF Error: {e}")

st.markdown("<br><br><br><br>", unsafe_allow_html=True)
